# Generated by Django 5.1 on 2024-08-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(upload_to='media/images/')),
                ('labels', models.FileField(upload_to='media/labels/')),
            ],
        ),
    ]
