# Generated by Django 5.1 on 2024-08-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnose',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='diagnose',
            name='filename',
            field=models.CharField(default='default_filename', max_length=255),
        ),
    ]
