# Generated by Django 5.1 on 2024-08-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_create_date_diagnose_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='labels',
            field=models.FileField(upload_to='labels/'),
        ),
    ]
