# Generated by Django 5.1 on 2024-08-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_diagnose_images_alter_diagnose_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
